// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArtoIy_riKyYeyVAF2NvuMc4p-N9VPNHM',
    appId: '1:48963002232:web:029b03f548ebe94eb1f28d',
    messagingSenderId: '48963002232',
    projectId: 'chocolatemyapp',
    authDomain: 'chocolatemyapp.firebaseapp.com',
    storageBucket: 'chocolatemyapp.firebasestorage.app',
    measurementId: 'G-T9BBT86VKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRij5WXscCcVr_BWLWWrCJI3hogD_j6F8',
    appId: '1:48963002232:android:82a3309accd9a060b1f28d',
    messagingSenderId: '48963002232',
    projectId: 'chocolatemyapp',
    storageBucket: 'chocolatemyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7gxSiqaUCYYuLWvG4ZAv5CpmLpVyYF48',
    appId: '1:48963002232:ios:f8f4e3e2407ae203b1f28d',
    messagingSenderId: '48963002232',
    projectId: 'chocolatemyapp',
    storageBucket: 'chocolatemyapp.firebasestorage.app',
    iosBundleId: 'com.example.chocolate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7gxSiqaUCYYuLWvG4ZAv5CpmLpVyYF48',
    appId: '1:48963002232:ios:f8f4e3e2407ae203b1f28d',
    messagingSenderId: '48963002232',
    projectId: 'chocolatemyapp',
    storageBucket: 'chocolatemyapp.firebasestorage.app',
    iosBundleId: 'com.example.chocolate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArtoIy_riKyYeyVAF2NvuMc4p-N9VPNHM',
    appId: '1:48963002232:web:c479998b9c5a73deb1f28d',
    messagingSenderId: '48963002232',
    projectId: 'chocolatemyapp',
    authDomain: 'chocolatemyapp.firebaseapp.com',
    storageBucket: 'chocolatemyapp.firebasestorage.app',
    measurementId: 'G-MHDJ2MXMW5',
  );
}
